### ISSUE TITLE
Save doesn't work and freezes the application on OSX

### ISSUE THREAD

**Issue by sonnyp** [DFRobot/Visual-Servo-Controller#1]
Thanks for great piece of software, having a lot of fun!
When I hit save, nothing happens and application freezes on OSX Yosemite but I can still quit without killing it.

**Comment by sonnyp** [comment]
Happened once can't reproduce now :/

**Comment by HuoSen** [comment]
:hamster:  bug is hard to reproduce! Well, never heard it before, but will keep an eye open, thanks.

**Comment by sonnyp** [comment]
Found a way to reproduce every time.
Open the app, and click open.

Let me know if I can help debug this.
